version: "3.9"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_controllers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    networks:
      - app_network

  app:
    image: movie_fastapi
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://postgres:mysecretpassword@db:5432/my_controllers"  # Aquí usamos el nombre del contenedor `db`
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge